{
  "version": 1,
  "Resources": [
    {
      "TargetService": {
        "Type": "AWS::ECS::Service",
        "Properties": {
          "TaskDefinition": "arn:aws:ecs:ap-southeast-2:687069305167:task-definition/nginx-red-login-fargate:2",
          "LoadBalancerInfo": {
            "ContainerName": "demo-ecs-bg",
            "ContainerPort": 80
          }
        }
      }
    }
  ]
}